### ISSUE TITLE
forEach would be good here

### ISSUE THREAD

**Issue by soggybag** [tsamantanis/FEW1.2-Break-out#1]
https://github.com/tsamantanis/FEW1.2-Break-out/blob/c0941d7711e21bbab5b1cd6222c076b697d07eac/Bricks.js#L39

This looks good. Great idea to put all of the bricks in a single array. While for loops are good and core to the language you can level up your skills by using array methods like forEach, map, filter, and reduce. 

In this case forEach would be the best choice here.

**Comment by tsamantanis** [comment]
Done!
